### ISSUE TITLE
Bug in start.sh script - bash path not set

### ISSUE THREAD

**Issue by tensafefrogs** [canad1an/cardano-stake-pool#2]
It looks like you missed a ~ in your start.sh script - it's writing a new .bashrc with just the path export line into /home/cardanouser/tmp/.bashrc

https://github.com/canad1an/cardano-stake-pool/blob/0695f9b8649a9a18c931290094469ad5bf72e671/sh/start.sh#L23

**Comment by tensafefrogs** [comment]
Although, after completing the setup, the .local/bin folder is empty, so not sure why that line is needed in the first place...

**Comment by canad1an** [comment]
Thank you, I have updated the start.sh script to include the ~/
It is used to build the binaries, which will ultimately be moved to /usr/local/bin/ anyway.
Ultimately the steps are listed in this order for now since i'm still waiting for a completely stable release for ghc to work on the Pis. Until that day, it will build the unstable binaries, then you esentially copy over them using the stable binaries provided in this repo.
